variables:
  DOCKER_IMAGE: docker.io/nekoimi/webapp:latest
  GHCR_IMAGE: ghcr.io/nekoimi/webapp:latest

stages:
  - build
  - tag
  - push

build-job:
  stage: build
  only:
    - master
  tags:
    - docker
  script:
    - docker build -t $DOCKER_IMAGE .

tag-job:
  stage: tag
  only:
    - master
  tags:
    - docker
  script:
    - docker tag $DOCKER_IMAGE $GHCR_IMAGE

push-docker-job:
  stage: push
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
    - docker push $DOCKER_IMAGE

push-ghcr-job:
  stage: push
  only:
    - master
  tags:
    - docker
  script:
    - docker login -u $GHCR_USERNAME -p $GHCR_TOKEN
    - docker push $GHCR_IMAGE
