name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - example
      - LICENSE
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md
      - example
      - LICENSE

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: nekoimi/webapp:latest